export const breadcrumbTranslations: { [key: string]: string } = {
  dashboard: "Trang chủ",
  users: "Nhân sự",
  profile: "Hồ sơ",
  settings: "Cài đặt",
  services: "Dịch vụ",
  create_service: "Tạo mới dịch vụ",
  bookings: "Quản lý đơn dọn nhà",
  mail: "Phản hồi",
  transactions: "Giao dịch",
  schedule: "Lịch làm việc",
  manage_shift: "Quản lý ca làm việc",
  create_team: "Tạo tổ",
  schedule_list: "Tạo lịch làm việc",
  booking: "Đơn dọn nhà",
  exception: "Bổ sung nhân viên",
  bookings_exception: "Bổ sung nhân viên",
  refund: "Hoàn tiền - Bồi thường",
  fee: "Quản lý phí",
  create_fees: "Tạo mới phí",
  services_setting: "Danh sách các loại xe & nhà",
  create_truck_category: "Tạo mới loại xe",
  promotions: "Danh sách khuyến mãi",
  create_promotion: "Tạo mới khuyến mãi",
  accept_employee: "Xét duyệt nhân viên mới"
};
