export const breadcrumbTranslations: { [key: string]: string } = {
  dashboard: "Trang chủ",
  users: "Nhân sự",
  profile: "Hồ sơ",
  settings: "Cài đặt",
  services: "Dịch vụ",
  create_service: "Tạo mới dịch vụ",
  bookings: "Quản lý đơn dọn nhà",
  mail: "Phản hồi",
  transactions: "Giao dịch",
  schedule: "Lịch làm việc",
  create_shift: "Tạo ca làm việc",
  create_team: "Tạo tổ",
  schedule_list: "Tạo lịch làm việc",
  booking: "Đơn dọn nhà",
  exception: "Đơn chưa có nhân viên",
  bookings_exception: "Đơn chưa có nhân vi  ên",
  refund: "Bồi thường",
  fee: "Quản lý phí",
  create_fee: "Tạo mới phí",
};
