export const mails = [
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    name: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    subject: "Khiếu nại về dịch vụ",
    text: "Kính gửi bộ phận chăm sóc khách hàng,\n\nTôi rất thất vọng với chất lượng dịch vụ mà tôi đã nhận được ngày hôm qua. Nhân viên của quý công ty không hỗ trợ tôi một cách nhiệt tình và thái độ phục vụ rất thiếu chuyên nghiệp. Tôi mong muốn nhận được lời giải thích và cách khắc phục từ phía công ty.\n\nTrân trọng,\nNguyễn Văn A",
    date: "2023-10-22T09:00:00",
    read: true,
    labels: ["khiếu nại", "khách hàng"],
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    name: "Trần Thị B",
    email: "tranthib@example.com",
    subject: "Phản hồi về sản phẩm lỗi",
    text: "Chào quý công ty,\n\nSản phẩm tôi mua gần đây gặp vấn đề về chất lượng. Sau một tuần sử dụng, sản phẩm đã không hoạt động như mong đợi. Tôi yêu cầu được đổi sản phẩm mới hoặc hoàn tiền.\n\nCảm ơn,\nTrần Thị B",
    date: "2023-10-22T10:30:00",
    read: true,
    labels: ["khiếu nại", "khách hàng"],
  },
  {
    id: "3e7c3f6d-bdf5-46ae-8d90-171300f27ae2",
    name: "Lê Văn C",
    email: "levanc@example.com",
    subject: "Khiếu nại về dịch vụ giao hàng",
    text: "Kính gửi bộ phận vận chuyển,\n\nĐơn hàng của tôi đã bị giao trễ hơn 3 ngày so với thời gian dự kiến. Điều này đã ảnh hưởng đến kế hoạch của tôi. Tôi mong công ty xem xét và cải thiện dịch vụ giao hàng.\n\nTrân trọng,\nLê Văn C",
    date: "2023-04-10T11:45:00",
    read: false,
    labels: ["khiếu nại", "khách hàng"],
  },
  {
    id: "61c35085-72d7-42b4-8d62-738f700d4b92",
    name: "Giám đốc Nguyễn Thị D",
    email: "nguyenthid@example.com",
    subject: "Thông báo cuộc họp khẩn",
    text: "Tất cả nhân viên phòng kinh doanh hãy có mặt tại phòng họp số 1 vào lúc 8h sáng mai để thảo luận về chiến lược mới.\n\nTrân trọng,\nGiám đốc Nguyễn Thị D",
    date: "2023-03-25T13:15:00",
    read: false,
    labels: ["cuộc họp", "công việc", "từ sếp"],
  },
  {
    id: "8f7b5db9-d935-4e42-8e05-1f1d0a3dfb97",
    name: "Giám đốc Trần Văn E",
    email: "tranvane@example.com",
    subject: "Yêu cầu báo cáo tiến độ dự án",
    text: "Chào các bạn,\n\nTôi cần bản báo cáo tiến độ dự án ABC trước 17h hôm nay. Hãy đảm bảo mọi thông tin được cập nhật chính xác.\n\nTrân trọng,\nGiám đốc Trần Văn E",
    date: "2023-03-10T15:00:00",
    read: false,
    labels: ["công việc", "quan trọng", "từ sếp"],
  },
  {
    id: "1f0f2c02-e299-40de-9b1d-86ef9e42126b",
    name: "Phạm Thị F",
    email: "phamthif@example.com",
    subject: "Phản hồi về dịch vụ hỗ trợ",
    text: "Kính gửi bộ phận hỗ trợ kỹ thuật,\n\nTôi đã liên hệ với bộ phận hỗ trợ nhưng chưa nhận được phản hồi. Vui lòng kiểm tra và giúp tôi giải quyết vấn đề sớm nhất.\n\nCảm ơn,\nPhạm Thị F",
    date: "2023-02-15T16:30:00",
    read: false,
    labels: ["khiếu nại", "khách hàng"],
  },
  {
    id: "17c0a96d-4415-42b1-8b4f-764efab57f66",
    name: "Giám đốc Lê Hoàng G",
    email: "lehoangg@example.com",
    subject: "Kế hoạch triển khai dự án mới",
    text: "Chào mọi người,\n\nChúng ta sẽ bắt đầu triển khai dự án mới vào tuần tới. Hãy chuẩn bị tài liệu và kế hoạch chi tiết để thảo luận trong cuộc họp ngày mai.\n\nTrân trọng,\nGiám đốc Lê Hoàng G",
    date: "2023-01-28T17:45:00",
    read: false,
    labels: ["cuộc họp", "công việc", "từ sếp"],
  },
  {
    id: "2f0130cb-39fc-44c4-bb3c-0a4337edaaab",
    name: "Ngô Thị H",
    email: "ngothih@example.com",
    subject: "Khiếu nại về thanh toán",
    text: "Kính gửi bộ phận kế toán,\n\nTôi đã thanh toán hóa đơn nhưng hệ thống vẫn báo chưa nhận được. Vui lòng kiểm tra và xác nhận lại cho tôi.\n\nCảm ơn,\nNgô Thị H",
    date: "2022-12-20T18:30:00",
    read: false,
    labels: ["khiếu nại", "khách hàng"],
  },
  {
    id: "de305d54-75b4-431b-adb2-eb6b9e546014",
    name: "Giám đốc Phạm Văn I",
    email: "phamvani@example.com",
    subject: "Đánh giá hiệu suất quý",
    text: "Chào đội ngũ,\n\nChúng ta sẽ tiến hành đánh giá hiệu suất làm việc quý này vào tuần tới. Mọi người hãy chuẩn bị báo cáo cá nhân và gửi về cho tôi trước thứ Sáu.\n\nTrân trọng,\nGiám đốc Phạm Văn I",
    date: "2022-11-30T19:15:00",
    read: false,
    labels: ["công việc", "từ sếp"],
  },
  {
    id: "7dd90c63-00f6-40f3-bd87-5060a24e8ee7",
    name: "Đặng Thị J",
    email: "dangthij@example.com",
    subject: "Phản ánh về thái độ nhân viên",
    text: "Kính gửi quản lý,\n\nTôi muốn phản ánh về thái độ phục vụ của nhân viên tại chi nhánh X. Họ không nhiệt tình và thiếu chuyên nghiệp.\n\nMong quý công ty xem xét và cải thiện dịch vụ.\n\nTrân trọng,\nĐặng Thị J",
    date: "2022-11-05T20:30:00",
    read: false,
    labels: ["khiếu nại", "khách hàng"],
  },
  {
    id: "99a88f78-3eb4-4d87-87b7-7b15a49a0a05",
    name: "Giám đốc Trương Minh K",
    email: "truongminhk@example.com",
    subject: "Thông báo nghỉ lễ",
    text: "Chào tất cả nhân viên,\n\nCông ty sẽ nghỉ lễ Tết Dương lịch từ ngày 31/12 đến hết ngày 02/01. Mọi người hãy sắp xếp công việc và bàn giao trước khi nghỉ.\n\nChúc mọi người kỳ nghỉ vui vẻ!\n\nTrân trọng,\nGiám đốc Trương Minh K",
    date: "2022-10-22T09:30:00",
    read: true,
    labels: ["thông báo", "công việc", "từ sếp"],
  },
];

export type Mail = (typeof mails)[number];
