export enum BookingStateAssign {
    WAITING = "WAITING",
    ASSIGNED = "ASSIGNED",
    ENROUTE = "ENROUTE",
    ARRIVED = "ARRIVED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    ROUND_TRIP = "ROUND_TRIP",
    CONFIRM = "CONFIRM",
    SUGGESTED = "SUGGESTED",
    CANCELLED = "CANCELLED",
    REFUNDED = "REFUNDED",
    REVIEWED = "REVIEWED",
    IN_TRANSIT = "IN_TRANSIT",
    DELIVERED = "DELIVERED",
    UNLOAD = "UNLOAD"
}
